# Generated by Django 5.0.1 on 2024-01-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_customuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
